---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: delete-namespace
  namespace: kuttl-test-delete-namespace
status:
  instances:
    - name: instance1
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kuttl-test-delete-namespace
  labels:
    ivory-operator.highgo.com/cluster: delete-namespace
    ivory-operator.highgo.com/pgbackrest-backup: replica-create
status:
  succeeded: 1
