apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: replica-read
status:
  instances:
    - name: instance1
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: replica-read-replicas
