apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: exporter
spec:
  postgresVersion: 15
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.2-0
