---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: delete
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
    ivory-operator.highgo.com/pgbackrest-backup: replica-create
status:
  succeeded: 1
