---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
---
# Patroni DCS objects are not owned by the PostgresCluster.
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete
