---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: delete-not-running
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
---
# Patroni DCS objects are not owned by the IvoryCluster.
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
---
apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: delete-not-running
