---
# This pgupgrade is invalid and should get that condition (even with no cluster)
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IVYUpgrade
metadata:
  name: major-upgrade-do-it
spec:
  fromPostgresVersion: ${KUTTL_PG_VERSION}
  toPostgresVersion: ${KUTTL_PG_VERSION}
  postgresClusterName: major-upgrade
