---
# This upgrade is valid, but has no pgcluster to work on and should get that condition
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IVYUpgrade
metadata:
  name: major-upgrade-do-it
spec:
  fromPostgresVersion: ${KUTTL_PG_UPGRADE_FROM_VERSION}
  toPostgresVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
  postgresClusterName: major-upgrade
