---
# This upgrade is valid, but has no pgcluster to work on and should get that condition
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvyUpgrade
metadata:
  name: major-upgrade-do-it
spec:
  fromIvoryVersion: ${KUTTL_PG_UPGRADE_FROM_VERSION}
  toIvoryVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
  ivoryclusterName: major-upgrade
