---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvyUpgrade
metadata:
  name: major-upgrade-do-it
status:
  conditions:
  - type:   "Progressing"
    status: "False"
    reason: "PGClusterNotFound"
