---
# Create a cluster that is already at the correct version
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: major-upgrade
spec:
  postgresVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
  instances:
    - dataVolumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
