---
# Since the cluster is missing the annotation, we get this condition
apiVersion: ivory-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: major-upgrade-do-it
status:
  conditions:
  - type:   "Progressing"
    status: "False"
    reason: "PGClusterMissingRequiredAnnotation"
