---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: delete-switchover-with-timestamp
status:
  instances:
    - name: instance1
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
---
# Patroni labels and readiness happen separately.
# The next step expects to find pods by their role label; wait for them here.
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete-switchover-with-timestamp
    ivory-operator.highgo.com/role: master
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete-switchover-with-timestamp
    ivory-operator.highgo.com/role: replica
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ivory-operator.highgo.com/cluster: delete-switchover-with-timestamp
    ivory-operator.highgo.com/pgbackrest-backup: replica-create
status:
  succeeded: 1
