apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: proxied
  labels: { ivory-operator-test: kuttl }
spec:
  postgresVersion: ${KUTTL_PG_VERSION}
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
  proxy:
    pgBouncer:
      replicas: 1
