apiVersion: ivory-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: owner1
---
apiVersion: ivory-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: owner2
