---
# Wait for the replica backup to complete.
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: original
status:
  pgbackrest:
    repos:
    - name: repo1
      replicaCreateBackupComplete: true
      stanzaCreated: true
