---
# Clone the cluster using a pgBackRest restore.
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: clone-one
  labels: { ivory-operator-test: kuttl }
spec:
  dataSource:
    postgresCluster:
      clusterName: original
      repoName: repo1

  postgresVersion: ${KUTTL_PG_VERSION}
  instances:
    - dataVolumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
