---
# Wait for the restore to complete and the cluster to come online.
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: original
status:
  instances:
    - name: '00'
      replicas: 2
      readyReplicas: 2
      updatedReplicas: 2
  pgbackrest:
    restore:
      id: one
      finished: true
