---
# Confirm that the replica is streaming from the primary.
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      REPLICA=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            ivory-operator.highgo.com/cluster=original,
            ivory-operator.highgo.com/role=replica'
      )

      kubectl exec --stdin --namespace "${NAMESPACE}" "${REPLICA}" \
        -- psql -qb original --set ON_ERROR_STOP=1 \
          --file=- <<'SQL'
        DO $$
        BEGIN
          PERFORM * FROM pg_stat_wal_receiver WHERE status = 'streaming';
          ASSERT FOUND, 'expected streaming replication';
        END $$
      SQL
