---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: interfaced
status:
  instances:
    - name: instance1
      replicas: 1
      readyReplicas: 1
      updatedReplicas: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: interfaced-pgadmin
status:
  replicas: 1
  readyReplicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
