namespace: ivory-operator

commonLabels:
  ivory-operator.highgo.com/control-plane: ivory-operator

bases:
- ../crd
- ../rbac/namespace
- ../manager

patches:
- path: manager-target.yaml

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.4.0-0
