apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: cluster-migrate
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: cluster-migrate
    ivory-operator.highgo.com/data: postgres
    ivory-operator.highgo.com/instance-set: instance1
    ivory-operator.highgo.com/role: master
status:
  phase: Running
