# We know that the PVC sizes have change so now we can check that they have been
# updated to have the expected size
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-up
    ivory-operator.highgo.com/instance-set: instance1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-up
    ivory-operator.highgo.com/data: pgbackrest
    ivory-operator.highgo.com/pgbackrest-repo: repo1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
