apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: resize-volume-down
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-down
    ivory-operator.highgo.com/pgbackrest-backup: replica-create
status:
  succeeded: 1
---
apiVersion: v1
kind: Service
metadata:
  name: resize-volume-down-primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-down
    ivory-operator.highgo.com/instance-set: instance1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-down
    ivory-operator.highgo.com/data: pgbackrest
    ivory-operator.highgo.com/pgbackrest-repo: repo1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
