apiVersion: v1
kind: Event
type: Warning
involvedObject:
  apiVersion: ivory-operator.highgo.com/v1beta1
  kind: IvoryCluster
  name: resize-volume-down
reason: PersistentVolumeError
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-down
    ivory-operator.highgo.com/instance-set: instance1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ivory-operator.highgo.com/cluster: resize-volume-down
    ivory-operator.highgo.com/data: pgbackrest
    ivory-operator.highgo.com/pgbackrest-repo: repo1
spec:
  resources:
    requests:
      storage: 2Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
