apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: scaledown
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
