apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: scaledown1
status:
  instances:
    - name: instance1
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: scaledown1
    ivory-operator.highgo.com/instance-set: instance1
    ivory-operator.highgo.com/role: master
status:
  phase: Running
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.highgo.com/cluster: scaledown1
    ivory-operator.highgo.com/instance-set: instance1
    ivory-operator.highgo.com/role: replica
status:
  phase: Running
