---
# Wait for the instances to be ready and the replica backup to complete
# by waiting for the status to signal pods ready and pgbackrest stanza created
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: wal-pvc-ivyupgrade
spec:
  postgresVersion: ${KUTTL_PG_UPGRADE_FROM_VERSION}
status:
  instances:
    - name: '00'
      replicas: 3
      readyReplicas: 3
      updatedReplicas: 3
  pgbackrest:
    repos:
    - name: repo1
      replicaCreateBackupComplete: true
      stanzaCreated: true
---
# Even when the cluster exists, the pgupgrade is not progressing because the cluster is not shutdown
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvyUpgrade
metadata:
  name: wal-pvc-ivyupgrade-do-it
status:
  conditions:
  - type:   "Progressing"
    status: "False"
    reason: "PGClusterNotShutdown"
