---
# Now that the postgres cluster is shut down and annotated, the pgupgrade
# can finish reconciling. We know the reconciling is complete when
# the pgupgrade status is succeeded and the postgres cluster status
# has the updated version.
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvyUpgrade
metadata:
  name: wal-pvc-ivyupgrade-do-it
status:
  conditions:
  - type:   "Progressing"
    status: "False"
  - type:   "Succeeded"
    status: "True"
---
apiVersion: ivory-operator.highgo.com/v1beta1
kind: IvoryCluster
metadata:
  name: wal-pvc-ivyupgrade
status:
  postgresVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
