---
# Once the pgupgrade is finished, update the version and set shutdown to false
# in the postgres cluster
apiVersion: ivory-operator.highgo.com/v1beta1
kind: PostgresCluster
metadata:
  name: wal-pvc-pgupgrade
spec:
  postgresVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
  shutdown: false
